import { ArrowLeft, Braces, Copy, ExternalLink, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";

const VIDEO = "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260212_043536_e0d3c69f-5c0c-4533-8395-fbe962587446.mp4";
const example = `GET /api/trpc/airfare.index?input={"json":{"route":"PNQ-DEL","departureDate":"2026-09-14","historyDays":30}}`;

export default function ApiDocs() {
  const copyExample = async () => { await navigator.clipboard?.writeText(example); toast.success("Request copied"); };
  return <div className="intel-page api-page"><div className="dashboard-ambient" aria-hidden="true"><video className="dashboard-background-video" autoPlay muted loop playsInline preload="auto" src={VIDEO} /><div className="dashboard-video-shade" /></div><header className="dashboard-header intel-header"><Link href="/" className="dashboard-back"><ArrowLeft size={15} /> Back to AEROVA</Link><div className="dashboard-title-lockup"><span className="dashboard-kicker">A / 08 — Machine-readable interface</span><h1>Index <span>API</span></h1></div><Link href="/dashboard" className="dashboard-refresh">Open live index <ExternalLink size={14} /></Link></header><main className="intel-main"><section className="intel-hero"><p className="dashboard-kicker">AEROVA / public contract</p><h2>Use the same signal in your own analysis.</h2><p>The dashboard and downstream consumers use one typed procedure. It returns the current observed index, stored trend snapshots, route and carrier summaries, quality signals, and transparent environment metadata.</p></section><section className="api-callout glass-card"><div className="dashboard-panel-head"><div><p className="dashboard-kicker">Endpoint</p><h3>airfare.index</h3></div><Braces size={16} /></div><code>{example}</code><button className="dashboard-refresh" onClick={copyExample}><Copy size={14} /> Copy request</button></section><section className="intel-grid"><div className="intel-card glass-card"><div className="dashboard-panel-head"><div><p className="dashboard-kicker">Input contract</p><h3>Query controls</h3></div></div><div className="api-field-list"><div><b>route</b><span>PNQ-DEL, BOM-DEL, DEL-BLR, HYD-DEL, or network</span></div><div><b>departureDate</b><span>ISO date for the requested travel date</span></div><div><b>airline</b><span>Optional returned-carrier filter</span></div><div><b>historyDays</b><span>7, 30, 90, or 365 stored days</span></div></div></div><div className="intel-card glass-card"><div className="dashboard-panel-head"><div><p className="dashboard-kicker">Output contract</p><h3>What is returned</h3></div></div><div className="api-field-list"><div><b>networkIndexValue</b><span>Base-100 observed fare index</span></div><div><b>routeSummary</b><span>Median, average, min, max, and movement</span></div><div><b>history</b><span>Persisted snapshots only</span></div><div><b>anomalies</b><span>Deterministic IQR quality flags</span></div></div></div></section><section className="intel-card glass-card"><div className="dashboard-panel-head"><div><p className="dashboard-kicker">Integrity boundary</p><h3>Test data is visible in every response</h3></div><ShieldCheck size={16} /></div><p>The current source is Duffel Developer Test API. AEROVA does not imply that test offers represent the Indian market or official CPI. Production consumers should only interpret the index after approved live sources and a reference validation series are connected.</p></section></main></div>;
}
